### ISSUE TITLE
General Task

### ISSUE THREAD

**Issue by SuzyQuant** [TaoFruit/hackneyuniversity#18]
1. Create the table of contents per repo in [NoteHive](https://github.com/NoteHive).
2. Create the contents of the following guides per repo in [NoteHive](https://github.com/NoteHive).

<hr>

- [ ] [Dream Guide](https://github.com/TaoFruit/hackneyuniversity/issues/2)
- [ ] [Curiosity Guide](https://github.com/TaoFruit/hackneyuniversity/issues/3)
- [ ] [STEAM Guide](https://github.com/TaoFruit/hackneyuniversity/issues/4)
- [ ] [Social Guide](https://github.com/TaoFruit/hackneyuniversity/issues/5)
- [ ] [Design Guide](https://github.com/TaoFruit/hackneyuniversity/issues/6)
- [ ] [Fitness Guide](https://github.com/TaoFruit/hackneyuniversity/issues/7)
- [ ] [Behavioral Guide](https://github.com/TaoFruit/hackneyuniversity/issues/8)
- [ ] [Lifestyle Guide](https://github.com/TaoFruit/hackneyuniversity/issues/9)
- [ ] [Research Guide](https://github.com/TaoFruit/hackneyuniversity/issues/10)
- [ ] [Performance Guide](https://github.com/TaoFruit/hackneyuniversity/issues/11)
- [ ] [Development Guide - Technical](https://github.com/TaoFruit/hackneyuniversity/issues/12)
- [ ] [Mindfulness Guide](https://github.com/TaoFruit/hackneyuniversity/issues/13)
- [ ] [Thought Leadership - Aptitude](https://github.com/TaoFruit/hackneyuniversity/issues/14)
- [ ] [Humanities Guide](https://github.com/TaoFruit/hackneyuniversity/issues/15)
- [ ] [Leadership Guide](https://github.com/TaoFruit/hackneyuniversity/issues/16)
- [ ] [Experience Guide - Internships & SMILE Spaces](https://github.com/TaoFruit/hackneyuniversity/issues/17)
